services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: TotalGambit123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: development
      JWT_SECRET: "ptJWL3uEa_U9UqeQCONgileRn6uxzLCVTapwWaGgvC_IhDBeyr0n_kHlKwm9-_RcfoZ1sdWIkoETUzCUVAv4PQ"
      JWT_ISSUER: localhost
      JWT_AUDIENCE: localhost
      DB_HOST: db
      DB_PORT: 1433
      DB_INSTANCENAME: ""
      DB_DATABASE: Total_Gambit
      DB_USERNAME: sa
      DB_PASSWORD: TotalGambit123
    depends_on:
      - db